services:
  # Backend service - API and WebSocket only
  project-colab-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - project-colab-network

  # Client 1 - React app
  project-colab-client-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - project-colab-network
    depends_on:
      - project-colab-backend

  # Client 2 - React app
  project-colab-client-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - project-colab-network
    depends_on:
      - project-colab-backend

  # Client 3 - React app
  project-colab-client-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - project-colab-network
    depends_on:
      - project-colab-backend

networks:
  project-colab-network:
    driver: bridge
