services:
  # Backend service - API and WebSocket only
  project-colab-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - BACKEND_ONLY=true
    restart: unless-stopped
    networks:
      - project-colab-network

  # Single client service - React app
  project-colab-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REACT_APP_CLIENT_ID=client-1
      - REACT_APP_PORT=8081
    restart: unless-stopped
    networks:
      - project-colab-network
    depends_on:
      - project-colab-backend

networks:
  project-colab-network:
    driver: bridge
